// <auto-generated />
using System;
using CustomPropertyDemo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CustomPropertyDemo.Migrations
{
    [DbContext(typeof(SampleContext))]
    partial class SampleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CustomPropertyDemo.Author", b =>
                {
                    b.Property<int>("AutorCode")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("AutorCode");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("CustomPropertyDemo.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AuthorAutorCode");

                    b.Property<string>("Title")
                        .HasColumnName("BookName")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("BookId");

                    b.HasIndex("AuthorAutorCode");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("CustomPropertyDemo.Writer", b =>
                {
                    b.Property<Guid>("WriterId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LastName");

                    b.HasKey("WriterId");

                    b.ToTable("Writer","dbo");
                });

            modelBuilder.Entity("CustomPropertyDemo.Book", b =>
                {
                    b.HasOne("CustomPropertyDemo.Author", "Author")
                        .WithMany("Titles")
                        .HasForeignKey("AuthorAutorCode");
                });
#pragma warning restore 612, 618
        }
    }
}
